plugpikinakata_srcs = files(
    'genteki.cpp',
    'nakatacode.cpp',
    'nlibfunction.cpp',
    'nlibgeometry.cpp',
    'nlibgeometry3d.cpp',
    'nlibgraphics.cpp',
    'nlibmath.cpp',
    'nlibspline.cpp',
    'nlibsystem.cpp',
    'panianimator.cpp',
    'panipikianimmgr.cpp',
    'panitekianimator.cpp',
    'panitestsection.cpp',
    'paraparameters.cpp',
    'pcamcamera.cpp',
    'pcamcameramanager.cpp',
    'pcammotionevents.cpp',
    'pcamcameraparameters.cpp',
    'peve.cpp',
    'peveconditions.cpp',
    'pevemotionevents.cpp',
    'tai.cpp',
    'taiattackactions.cpp',
    'taibasicactions.cpp',
    'taichappy.cpp',
    'taicollec.cpp',
    'taicollisionactions.cpp',
    'taieffectactions.cpp',
    'taiiwagen.cpp',
    'taijudgementactions.cpp',
    'taikinoko.cpp',
    'taimessageactions.cpp',
    'taimizinko.cpp',
    'taimotionactions.cpp',
    'taimoveactions.cpp',
    'tainapkid.cpp',
    'taiotimoti.cpp',
    'taipalm.cpp',
    'taireactionactions.cpp',
    'taiswallow.cpp',
    'taishell.cpp',
    'taitimeractions.cpp',
    'taiwaitactions.cpp',
    'teki.cpp',
    'tekianimationmanager.cpp',
    'tekibteki.cpp',
    'tekiconditions.cpp',
    'tekievent.cpp',
    'tekiinteraction.cpp',
    'tekimgr.cpp',
    'tekinakata.cpp',
    'tekinteki.cpp',
    'tekiparameters.cpp',
    'tekipersonality.cpp',
    'tekistrategy.cpp',
)


plugpikinakata_lib = static_library('plugPikiNakata',
    include_directories: project_includes,
    pic: false,
    dependencies: libporpoise_dep,
    sources: [plugpikinakata_srcs],
    native: build_target != 'gc'
)

pikmin_libs += plugpikinakata_lib