plugpikiyamashita_srcs = files(
    'gameCourseClear.cpp',
    'gameStageClear.cpp',
    'gameCredits.cpp',
    'zenMath.cpp',
    'effectMgr.cpp',
    'particleGenerator.cpp',
    'particleLoader.cpp',
    'solidField.cpp',
    'particleManager.cpp',
    'particleMdlManager.cpp',
    'bBoardColourAnim.cpp',
    'simpleParticle.cpp',
    'tekiyteki.cpp',
    'tekiyamashita.cpp',
    'TAIanimation.cpp',
    'TAItank.cpp',
    'TAImar.cpp',
    'TAIAreaction.cpp',
    'TAIAmove.cpp',
    'TAIAmotion.cpp',
    'TAIAjudge.cpp',
    'TAIAattack.cpp',
    'P2DGrafContext.cpp',
    'P2DOrthoGraph.cpp',
    'P2DPerspGraph.cpp',
    'P2DPane.cpp',
    'P2DPicture.cpp',
    'P2DScreen.cpp',
    'P2DStream.cpp',
    'PSUList.cpp',
    'PUTRect.cpp',
    'P2DWindow.cpp',
    'P2DTextBox.cpp',
    'P2DPrint.cpp',
    'P2DFont.cpp',
    'drawGameInfo.cpp',
    'zenGraphics.cpp',
    'drawContainer.cpp',
    'drawCommon.cpp',
    'zenController.cpp',
    'drawHurryUp.cpp',
    'texAnim.cpp',
    'drawAccount.cpp',
    'drawMenu.cpp',
    'TAIeffectAttack.cpp',
    'TAIbeatle.cpp',
    'menuPanelMgr.cpp',
    'TAIkabekuiA.cpp',
    'TAIkabekuiB.cpp',
    'TAIkabekuiC.cpp',
    'TAItamago.cpp',
    'TAIdororo.cpp',
    'TAIhibaA.cpp',
    'TAIAeffect.cpp',
    'TAImiurin.cpp',
    'ptclGenPack.cpp',
    'drawProgre.cpp',
    'spectrumCursorMgr.cpp',
    'drawWorldMap.cpp',
    'drawCountDown.cpp',
    'drawGameOver.cpp',
    'yai.cpp',
    'effectMgr2D.cpp',
    'drawWMPause.cpp',
    'TAIusuba.cpp',
    'TAIotama.cpp',
    'drawCMcourseSelect.cpp',
    'drawCMtitle.cpp',
    'drawCMscore.cpp',
    'drawCMbest.cpp',
    'drawCMresult.cpp',
    'drawMenuBase.cpp',
    'drawHiScore.cpp',
    'damageEffect.cpp',
    'alphaWipe.cpp',
    'drawUfoParts.cpp',
    'zenSys.cpp',
    'drawSaveMes.cpp',
    'drawSaveFailure.cpp',
    'drawFinalResult.cpp',
    'drawOptionSave.cpp',
)


plugpikiyamashita_lib = static_library('plugPikiYamashita',
    include_directories: project_includes,
    pic: false,
    dependencies: libporpoise_dep,
    sources: [plugpikiyamashita_srcs],
    native: build_target != 'gc'
)

pikmin_libs += plugpikiyamashita_lib