jaudio_srcs = files(
    'dummyprobe.c',
    'memory.c',
    'aictrl.c',
    'sample.c',
    'dummyrom.c',
    'audiothread.c',
    'streamctrl.c',
    'dspbuf.c',
    'cpubuf.c',
    'playercall.c',
    'dvdthread.c',
    'rate.c',
    'audiomesg.c',
    'stackchecker.c',
    'dspboot.c',
    'dspproc.c',
    'dsptask.c',
    'osdsp.c',
    'osdsp_task.c',
    'ipldec.c',
    'dsp_cardunlock.c',
    'driverinterface.c',
    'dspdriver.c',
    'dspinterface.c',
    'fxinterface.c',
    'bankread.c',
    'waveread.c',
    'connect.c',
    'tables.c',
    'bankdrv.c',
    'random.c',
    'aramcall.c',
    'ja_calc.c',
    'fat.c',
    'cmdstack.c',
    'virload.c',
    'heapctrl.c',
    'jammain_2.c',
    'midplay.c',
    'noteon.c',
    'seqsetup.c',
    'centcalc.c',
    'jamosc.c',
    'oneshot.c',
    'interface.c',
    'verysimple.c',
    'app_inter.c',
    'pikiinter.c',
    'piki_player.c',
    'piki_bgm.c',
    'piki_scene.c',
    'pikidemo.c',
    'file_seq.c',
    'cmdqueue.c',
    'filter3d.c',
    'syncstream.c',
    'bankloader.c',
    'interleave.c',
    'pikiseq.c',
    'hvqm_play.c',
)


jaudio_lib = static_library('jaudio',
    include_directories: project_includes,
    pic: false,
    c_args: ['-x', 'c++'],
    dependencies: libporpoise_dep,
    sources: [jaudio_srcs],
    native: build_target != 'gc'
)

pikmin_libs += jaudio_lib