plugpikikando_srcs = files(
    'omake.cpp',
    'radarInfo.cpp',
    'interactBattle.cpp',
    'interactGrab.cpp',
    'interactEtc.cpp',
    'interactPullout.cpp',
    'saiEvents.cpp',
    'simpleAI.cpp',
    'formationMgr.cpp',
    'globalShapes.cpp',
    'playerState.cpp',
    'gameDemo.cpp',
    'demoInvoker.cpp',
    'demoEvent.cpp',
    'resultFlag.cpp',
    'aiConstants.cpp',
    'kio.cpp',
    'keyConfig.cpp',
    'aiPerf.cpp',
    'courseDebug.cpp',
    'memStat.cpp',
    'collInfo.cpp',
    'complexCreature.cpp',
    'creature.cpp',
    'creatureCollision.cpp',
    'creatureCollPart.cpp',
    'creatureMove.cpp',
    'creatureStick.cpp',
    'dualCreature.cpp',
    'dynCreature.cpp',
    'eventListener.cpp',
    'fastGrid.cpp',
    'ropeCreature.cpp',
    'objectTypes.cpp',
    'pelletMgr.cpp',
    'animPellet.cpp',
    'genPellet.cpp',
    'pelletState.cpp',
    'workObject.cpp',
    'routeMgr.cpp',
    'seMgr.cpp',
    'seConstants.cpp',
    'soundMgr.cpp',
    'updateMgr.cpp',
    'cPlate.cpp',
    'aiStone.cpp',
    'aiActions.cpp',
    'aiAttack.cpp',
    'aiBore.cpp',
    'aiBoMake.cpp',
    'aiBou.cpp',
    'aiBridge.cpp',
    'aiBreakWall.cpp',
    'aiTransport.cpp',
    'aiKinoko.cpp',
    'aiChase.cpp',
    'aiCrowd.cpp',
    'aiDecoy.cpp',
    'aiEnter.cpp',
    'aiEscape.cpp',
    'aiExit.cpp',
    'aiMine.cpp',
    'aiFormation.cpp',
    'aiFree.cpp',
    'aiGoto.cpp',
    'aiGuard.cpp',
    'aiPick.cpp',
    'aiPickCreature.cpp',
    'aiPullout.cpp',
    'aiPush.cpp',
    'aiPut.cpp',
    'aiRandomBoid.cpp',
    'aiRescue.cpp',
    'aiRope.cpp',
    'aiShoot.cpp',
    'aiWatch.cpp',
    'aiWeed.cpp',
    'aiTable.cpp',
    'aiAction.cpp',
    'pikiInf.cpp',
    'piki.cpp',
    'odoMeter.cpp',
    'pikidoKill.cpp',
    'pikiMgr.cpp',
    'pikiState.cpp',
    'viewPiki.cpp',
    'conditions.cpp',
    'generator.cpp',
    'generatorCache.cpp',
    'objectMgr.cpp',
    'searchSystem.cpp',
    'smartPtr.cpp',
    'itemGem.cpp',
    'weedsItem.cpp',
    'kusaItem.cpp',
    'fishItem.cpp',
    'ufoItem.cpp',
    'ufoAnim.cpp',
    'bombItem.cpp',
    'goalItem.cpp',
    'pikiheadItem.cpp',
    'keyItem.cpp',
    'ropeItem.cpp',
    'seedItem.cpp',
    'genItem.cpp',
    'itemAI.cpp',
    'itemMgr.cpp',
    'itemObject.cpp',
    'mizuItem.cpp',
    'paniItemAnimator.cpp',
    'genNavi.cpp',
    'navi.cpp',
    'naviState.cpp',
    'naviDemoState.cpp',
    'gameCoreSection.cpp',
    'gmWin.cpp',
    'gameStat.cpp',
    'kmath.cpp',
    'uteffect.cpp',
    'kontroller.cpp',
    'mapcode.cpp',
    'utkando.cpp',
    'naviMgr.cpp',
    'genMapParts.cpp',
    'mapParts.cpp',
    'panipikianimator.cpp',
    'actor.cpp',
    'actorMgr.cpp',
    'genActor.cpp',
    'pikiInfo.cpp',
    'plantMgr.cpp',
    'paniPlantAnimator.cpp',
    'policeAI.cpp'
)


plugpikikando_lib = static_library('plugPikiKando',
    include_directories: project_includes,
    pic: false,
    dependencies: libporpoise_dep,
    sources: [plugpikikando_srcs],
    native: build_target != 'gc'
)

pikmin_libs += plugpikikando_lib